kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: asm
spec:
  selector:
    matchLabels:
      environment: asm
---
kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: aws
spec:
  selector:
    matchLabels:
      environment: aws
---
kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: onprem
spec:
  selector:
    matchLabels:
      environment: onprem
