apiVersion: clusterregistry.k8s.io/v1alpha1
kind: Cluster
metadata:
  name: anthos-gcp
  labels:
    environment: gcp
---
apiVersion: clusterregistry.k8s.io/v1alpha1
kind: Cluster
metadata:
  name: anthos-onprem
  labels:
    environment: onprem
